### ISSUE TITLE
Versioning services

### ISSUE THREAD

**Issue by craigmulligan** [Agile-IoT/Architecture#1]
As we begin to integrate all the agile services it's clear that we need to have a good idea of what version of each service is running. 

The current state when [running the stack](https://github.com/Agile-IoT/agile-resin) is that we just pull the latest images for each service from dockerhub and are therefore unaware if services have changed and what those changes are. 

To fix this we need to introduce some versioning mechanism to our agile services. A versioning mechanism will allow us to easily identify when a bug is introduced into the stack and which service + version + commit is likely the culprit, which should minimize compatibility issues :1st_place_medal: 

Here's how I propose we tackle this. 

* Decide on a versioning system I'd suggestion semantic as most are familiar with it. But in a nutshell it breaks changes into three types: 
```
1.MAJOR version when you make incompatible API changes,
1.MINOR version when you add functionality in a backwards-compatible manner, and
1.PATCH version when you make backwards-compatible bug fixes.
``` 

* Next we need to adopt an `agile convention` for commits. This doesn't have to be very strict but having uniformity will allow us to auto-generate changelogs. For example:

```
fix /devices/ endpoint

The /devices endpoint was only returning 3 devices as reported in issue #13

Change-Type: patch
```

* Once we have uniform commits we can auto-generate changelogs with a tool like [versionist](https://github.com/resin-io/versionist). (resin.io uses it in-house) Now we have a `CHANGELOG.md` for every service. 

* Next we'd want to tag every release to commit. ( we could add this functionality to versionist) but for now we can just manually. eg`git tag v1.0.0`

* Then for every release (or perhaps at the maintainer's discretion) they build and push the new release to dockerhub with the version as a tag. `eg /agileiot/agile-core-armv7l:1.0.0` if you had different variations of each version you could add with a `-suffix` like `eg /agileiot/agile-core-armv7l:1.0.0-wheezy` 

Thoughts? Ideas?

**Comment by rosogon** [comment]
I agree with this. One question: if every service has its own version number, how to track the compatibility between services?

**Comment by craigmulligan** [comment]
At the moment all the services are run together in https://github.com/Agile-IoT/agile-resin. From that repo, we manage which the version of each service that is at the HEAD of master. And only allow new versions to be included when they have been tested. 

So there aren't any surprise updates to services that break the stack. The idea isn't to allow incompatibility between services, it's to detect the incompatibility and know what has changed and where the problem is likely to have stemmed from.

However maybe it is useful to have an experimental branch (nightly build) on the `agile-resin` repo that just pulls the latest version for each service? Having people working on that would actually be super good to detect bugs before the get merged. 

What you think? @rosogon

**Comment by rosogon** [comment]
Ok, if I understood correctly, the docker compose file is like a "compatibility matrix".

The nightly build looks also a good idea. How much effort does it need for implementing?

**Comment by craigmulligan** [comment]
Exactly, I reckon the easiest would be using branches. The docker compose file on `master` which would require every image to be tagged to a version eg. `image: /agileiot/agile-core-armv7l:1.0.0`. then we'd have a `nightly` branch which would be identical to `master` but all the services would just pull the latest eg: `image: /agileiot/agile-core-armv7l:latest`.

So it'd require maintaining the compose file across two branches. *we could automate that process but maybe an over kill*?

**Comment by rosogon** [comment]
It looks so simple :)

Yes, I would say we don't need to automate that.

**Comment by rosogon** [comment]
I will start tagging the code and docker images as you propose. Regarding the commits convention, we'll need more agreement, I guess.

**Comment by cskiraly** [comment]
I agree with the versioning. Regarding fixing image tags in the compose file, this is the approach I've followed after the review demo in order to archive the setup, and it should work well.
It might still worth investigating whether we would gain from a meta-repo with git submodules ... at the moment I don't see it as being better, but lets keep it in mind.

**Comment by cskiraly** [comment]
For the record:
- repo is now https://github.com/Agile-IoT/agile-stack
- versionist had been added in https://github.com/Agile-IoT/agile-stack/pull/10
- versionist usage is described here https://github.com/Agile-IoT/agile-stack/blob/master/CONTRIBUTING.md
